apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: sweeper-sentinel
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: sweeper-sentinel
