# This rule is not used by the project sweeper-sentinel itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over sweepers.sentinel.cloudflavor.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sweeper-sentinel
    app.kubernetes.io/managed-by: kustomize
  name: sweepersentinel-admin-role
rules:
- apiGroups:
  - sweepers.sentinel.cloudflavor.io
  resources:
  - sweepersentinels
  verbs:
  - '*'
- apiGroups:
  - sweepers.sentinel.cloudflavor.io
  resources:
  - sweepersentinels/status
  verbs:
  - get
