apiVersion: sweeper.sweeper-sentinel.cloudflavor.io/v1
kind: SweeperSentinel
metadata:
  labels:
    app.kubernetes.io/name: sweeper-sentinel
    app.kubernetes.io/managed-by: kustomize
  name: sweepersentinel-sample
spec:
  ttl: "10m"
  targets:
    - apiVersion: "v1"
      kind: "Pod"
    - apiVersion: "apps/v1"
      kind: "Deployment"
    - apiVersion: "apps/v1"
      kind: "StatefulSet"
    - apiVersion: "apps/v1"
      kind: "DaemonSet"
    - apiVersion: "v1"
      kind: "Service"
    - apiVersion: "v1"
      kind: "ConfigMap"
    - apiVersion: "v1"
      kind: "Secret"
    - apiVersion: "v1"
      kind: "PersistentVolumeClaim"
    - apiVersion: "networking.k8s.io/v1"
      kind: "Ingress"
    - apiVersion: "batch/v1"
      kind: "Job"
    - apiVersion: "batch/v1"
      kind: "CronJob"
